#!/usr/bin/env node
/**
 * qa-runner.mjs — Generic Playwright QA Automation Runner
 *
 * Usage:
 *   node qa/qa-runner.mjs --url https://example.com --test smoke
 *   node qa/qa-runner.mjs --url http://localhost:5000 --test register --viewport mobile
 *
 * Options:
 *   --url           Base URL of the app to test (required)
 *   --test          Test to run: smoke | register | crud | admin | regression (default: "smoke")
 *   --viewport      Viewport: desktop | mobile (default: "desktop")
 *   --report-dir    Directory for screenshots and reports (default: "qa/qa-reports")
 *   --email         Test email for login/register (default: "qa-test@test.com")
 *   --password      Test password (default: "QaTest1234")
 *   --headless      Run browser headless (default: true)
 */

import { chromium } from "playwright";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = {};
  const raw = process.argv.slice(2);
  for (let i = 0; i < raw.length; i++) {
    if (raw[i].startsWith("--")) {
      const key = raw[i].slice(2);
      const val = raw[i + 1] && !raw[i + 1].startsWith("--") ? raw[i + 1] : true;
      args[key] = val;
      if (val !== true) i++;
    }
  }
  return {
    url: args.url || "http://localhost:5000",
    test: args.test || "smoke",
    viewport: args.viewport || "desktop",
    reportDir: args["report-dir"] || path.join(__dirname, "qa-reports"),
    email: args.email || "qa-test@test.com",
    password: args.password || "QaTest1234",
    headless: args.headless !== "false",
  };
}

const VIEWPORTS = {
  desktop: { width: 1280, height: 800 },
  mobile: { width: 375, height: 812 },
};

const RESULTS = { passed: 0, failed: 0, errors: [] };
let SCREENSHOT_COUNTER = 0;

async function screenshot(page, label) {
  SCREENSHOT_COUNTER++;
  const filename = `${String(SCREENSHOT_COUNTER).padStart(3, "0")}-${label
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")}.png`;
  const filepath = path.join(CONFIG.reportDir, "screenshots", filename);
  await page.screenshot({ path: filepath, fullPage: false });
  return filepath;
}

function check(label, condition, detail = "") {
  if (condition) {
    RESULTS.passed++;
    console.log(`  [PASS] ${label}`);
  } else {
    RESULTS.failed++;
    RESULTS.errors.push({ label, detail });
    console.log(`  [FAIL] ${label}${detail ? " — " + detail : ""}`);
  }
}

function generateReport(config, duration) {
  const total = RESULTS.passed + RESULTS.failed;
  const score = total > 0 ? Math.round((RESULTS.passed / total) * 100) : 100;
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const report = `# QA Report — ${config.test}
**Date:** ${new Date().toISOString()}
**URL:** ${config.url}
**Viewport:** ${config.viewport} (${VIEWPORTS[config.viewport].width}x${VIEWPORTS[config.viewport].height})
**Duration:** ${Math.round(duration / 1000)}s

---

### Health Score

| Category | Score | Notes |
|----------|-------|-------|
| Functional | ${score}/100 | ${RESULTS.passed}/${total} checks passed |
| Console | — | See console errors below |

### Results

${RESULTS.errors.map((e) => `- [FAIL] ${e.label}${e.detail ? ": " + e.detail : ""}`).join("\n") || "All checks passed."}

### Console Errors Detected

| Page | Error |
|------|-------|

---

*Report auto-generated by qa-runner.mjs*
`;

  const reportPath = path.join(config.reportDir, `qa-report-${config.test}-${timestamp}.md`);
  fs.writeFileSync(reportPath, report, "utf-8");
  console.log(`\nReport saved: ${reportPath}`);
  return { score, reportPath };
}

async function runSmokeTest(page, config) {
  console.log("\n--- Smoke Test ---");

  // 1. Landing page loads
  await page.goto(config.url, { waitUntil: "networkidle" });
  await screenshot(page, "landing-page");
  check("Landing page loads", !page.url().includes("error"));

  // 2. Health endpoint
  try {
    const resp = await page.request.get(`${config.url}/api/health`);
    check("Health endpoint responds", resp.ok());
  } catch {
    check("Health endpoint responds", false, "Could not reach /api/health");
  }

  // 3. Console errors check
  const consoleErrors = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") consoleErrors.push(msg.text());
  });
  await page.goto(config.url, { waitUntil: "networkidle" });
  check("No console errors on load", consoleErrors.length === 0,
    consoleErrors.length > 0 ? `Errors: ${consoleErrors.slice(0, 3).join("; ")}` : ""
  );
}

async function runRegisterTest(page, config) {
  console.log("\n--- Registration + Login Test ---");
  const timestamp = Date.now();
  const testEmail = `qa-${timestamp}@test.com`;

  // 1. Go to landing
  await page.goto(config.url, { waitUntil: "networkidle" });
  await screenshot(page, "register-landing");
  check("Landing loads for register", true);

  // 2. Find and click register button
  const registerBtn = page.locator('button, a', { hasText: /registr|crear cuenta|probá gratis|sign up|register/i }).first();
  const btnVisible = await registerBtn.isVisible().catch(() => false);
  check("Register button is visible", btnVisible);
  if (btnVisible) {
    await registerBtn.click();
    await page.waitForTimeout(1000);
    await screenshot(page, "register-modal");
  }

  // 3. Fill registration form
  const emailInput = page.locator('input[type="email"], input[name="email"]').first();
  const passInput = page.locator('input[type="password"]').first();
  const emailVisible = await emailInput.isVisible().catch(() => false);
  check("Registration form is accessible", emailVisible);

  if (emailVisible) {
    await emailInput.fill(testEmail);
    await passInput.fill(config.password);
    const submitBtn = page.locator('button[type="submit"], button:has-text("continuar"), button:has-text("registrarme")').first();
    const submitVisible = await submitBtn.isVisible().catch(() => false);
    if (submitVisible) {
      await submitBtn.click();
      await page.waitForTimeout(2000);
      await screenshot(page, "register-submitted");
    }
  }
}

async function runRegressionTest(page, config) {
  console.log("\n--- Regression Test (post-deploy smoke) ---");

  // 1. Landing loads
  await page.goto(config.url, { waitUntil: "networkidle" });
  await screenshot(page, "regression-landing");
  check("[REGRESSION] Landing loads", true);

  // 2. Health check
  try {
    const resp = await page.request.get(`${config.url}/api/health`);
    check("[REGRESSION] Health endpoint", resp.ok());
  } catch {
    check("[REGRESSION] Health endpoint", false, "Unreachable");
  }

  // 3. Login attempt
  const loginLink = page.locator('a, button', { hasText: /iniciar sesión|login|log in|ingresar/i }).first();
  const loginVisible = await loginLink.isVisible().catch(() => false);
  check("[REGRESSION] Login link visible", loginVisible);
}

const TEST_RUNNERS = {
  smoke: runSmokeTest,
  register: runRegisterTest,
  regression: runRegressionTest,
};

async function main() {
  const CONFIG = parseArgs();
  CONFIG.reportDir = path.resolve(CONFIG.reportDir);

  fs.mkdirSync(path.join(CONFIG.reportDir, "screenshots"), { recursive: true });

  console.log("═══════════════════════════════════════════════");
  console.log("  QA RUNNER — Playwright Automation");
  console.log("═══════════════════════════════════════════════");
  console.log(`  URL:       ${CONFIG.url}`);
  console.log(`  Test:      ${CONFIG.test}`);
  console.log(`  Viewport:  ${CONFIG.viewport}`);
  console.log(`  Headless:  ${CONFIG.headless}`);
  console.log("═══════════════════════════════════════════════");

  const start = Date.now();
  const browser = await chromium.launch({ headless: CONFIG.headless });
  const context = await browser.newContext({
    viewport: VIEWPORTS[CONFIG.viewport] || VIEWPORTS.desktop,
  });
  const page = await context.newPage();

  const runner = TEST_RUNNERS[CONFIG.test];
  if (!runner) {
    console.error(`Unknown test: ${CONFIG.test}. Available: ${Object.keys(TEST_RUNNERS).join(", ")}`);
    await browser.close();
    process.exit(1);
  }

  try {
    await runner(page, CONFIG);
  } catch (err) {
    console.error(`\n[ERROR] Test crashed: ${err.message}`);
    RESULTS.errors.push({ label: "Test execution", detail: err.message });
  }

  const duration = Date.now() - start;
  const { score } = generateReport(CONFIG, duration);

  await browser.close();

  console.log("\n═══════════════════════════════════════════════");
  console.log(`  SCORE: ${score}/100`);
  console.log(`  ${RESULTS.passed} passed, ${RESULTS.failed} failed`);
  console.log(`  Duration: ${Math.round(duration / 1000)}s`);
  console.log("═══════════════════════════════════════════════");

  process.exit(RESULTS.failed > 0 ? 1 : 0);
}

main();
